import { useSelector } from "react-redux";
import React from "react";
import Head from "next/head";
import { Box, TextField, Typography } from "@mui/material";

import SideBarComponent from "src/components/sideBar/sideBarComponent";
import {
  LoginCard,
  CustomSignInButton,
  LoginPageWrapper,
} from "./manageUser.style";
import ManageuserController from "./manageuser.controller";

export default function ManageUser() {
  const { getters, handlers } = ManageuserController();
  const { email, password, emailHelpertext, passwordHelpertext,isApiPending }=getters;
  const {
    validateEmail,
    handleSubmit,
    validatePassword,
  }=handlers;
  const home = useSelector((state) => state);

  return (
    <>
      <SideBarComponent>
        <LoginPageWrapper>
          <Head>
            <title>Mindpath ChatBot App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <LoginCard>
            <Typography
              sx={{ textAlign: "center", fontSize: "24px", fontWeight: "700" }}>
              Add User
            </Typography>
            <Box>
              <TextField
                sx={(theme) => ({
                  margin: theme.spacing(0.6),
                })}
                id="email"
                label="Email"
                variant="standard"
                autoComplete="off"
                fullWidth
                onChange={validateEmail}
                value={email.value}
                error={!email.isValid}
                helperText={emailHelpertext}
              />
            </Box>
            <Box>
              <TextField
                sx={(theme) => ({
                  margin: theme.spacing(0.6),
                })}
                id="password"
                label="Password"
                type="password"
                variant="standard"
                fullWidth
                onChange={validatePassword}
                value={password.value}
                error={!password.isValid}
                helperText={passwordHelpertext}
              />
            </Box>
            <Box>
              <CustomSignInButton
                variant="contained"
                type="submit"
                disabled={
                  !isApiPending &&
                  email.isValid && password.isValid
                    ? false
                    : true
                    
                }
                onClick={handleSubmit}
                >
                Add User
              </CustomSignInButton>
            </Box>
          </LoginCard>
        </LoginPageWrapper>
      </SideBarComponent>
    </>
  );
}
