name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Node.js and npm
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18

      # - name: Install project dependencies
      #   run: npm install

      # - name: Build project
      #   run: npm run build

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ls  /home/ec2-user/
            git clone https://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@github.com/singh12345akshay/Chatbot.git
            cd /home/ec2-user/Chatbot && sudo npm i && sudo npm run build &&
            nohup npm start &
              
            
      # - name: Executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd ~/home/ec2-user/Chatbot/Chatbot
      #       yarn/npm install
      #       yarn/npm build
      #       yarn/npm i serve
      #       serve -p 3000 build/
      # - name: Deploy to Server 1
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.EC2_HOST }}
      #     REMOTE_USER: ${{ secrets.EC2_USERNAME }}
      #     TARGET: "home/ec2-user/app"
      # - name: Deploy to my EC2 instance
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SOURCE: "./"
      #     REMOTE_HOST: ${{ secrets.EC2_HOST }}
      #     REMOTE_USER: ${{ secrets.EC2_USERNAME }}
      #     TARGET: "/home/ec2-user/p"
          
      # - name: Copy project files to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     source: .
      #     target: /home/ec2-user

      # - name: SSH into EC2 and restart the server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: 'cd /home/ec2-user && npm start'
