name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
      - uses: actions/checkout@v2 
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USERNAME}}

        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/Chatbot/Chatbot &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run build &&
              sudo pm2 stop ./dist/index.js &&
              sudo pm2 start ./dist/index.js
              '  
      # - name: Deploy to my EC2 instance
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SOURCE: "./"
      #     REMOTE_HOST: ${{ secrets.EC2_HOST }}
      #     REMOTE_USER: ${{ secrets.EC2_USERNAME }}
      #     TARGET: "/home/ec2-user/p"
          
      # - name: Copy project files to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     source: .
      #     target: /home/ec2-user

      - name: SSH into EC2 and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: 'cd /home/ec2-user && npm start'
